package apra.trainsgame;

public enum GameAction {
	PLAYER_1_UP, PLAYER_1_RIGHT, PLAYER_1_DOWN, PLAYER_1_LEFT, PLAYER_1_CW, PLAYER_1_CCW,
	PLAYER_2_UP, PLAYER_2_RIGHT, PLAYER_2_DOWN, PLAYER_2_LEFT, PLAYER_2_CW, PLAYER_2_CCW,
	GAME_RESTART, GAME_PAUSE, GAME_UNPAUSE, GAME_END
}
